
--CURDIR--/calls.fz:434:29: error 1: Call performed on a boxed (explicit 'ref') type not permitted here.
    yak "caseC3a: "; chck t.f.s "f#1 in oa type calls.caseC2.oa"     # ******  NEGATIVE TEST, causes ERROR!  ******
----------------------------^
The problem is that the call result type '(calls.this.type.caseC3.this.type.ref on).f' contains the outer, boxed type while the call will create the corresponding value type of the dynamic target type, which might be a different type inheriting from 'calls.caseC3.on'.
Type with boxed outer type: '(calls.this.type.caseC3.this.type.ref on).f'
Boxed outer type          : 'calls.this.type.caseC3.this.type.ref on'
To solve this, remove the use of 'ref' in the declaration of the type of the call target or add 'ref' to the declaration of the corresponding feature 'calls.caseC3.on' at --CURDIR--/calls.fz:419:5:
    on is
----^


--CURDIR--/calls.fz:435:29: error 2: Call performed on a boxed (explicit 'ref') type not permitted here.
    yak "caseC3a: "; chck t.f.s "f#2 in oa type calls.caseC2.oa"     # ******  NEGATIVE TEST, causes ERROR!  ******
----------------------------^
The problem is that the call result type '(calls.this.type.caseC3.this.type.ref on).f' contains the outer, boxed type while the call will create the corresponding value type of the dynamic target type, which might be a different type inheriting from 'calls.caseC3.on'.
Type with boxed outer type: '(calls.this.type.caseC3.this.type.ref on).f'
Boxed outer type          : 'calls.this.type.caseC3.this.type.ref on'
To solve this, remove the use of 'ref' in the declaration of the type of the call target or add 'ref' to the declaration of the corresponding feature 'calls.caseC3.on' at --CURDIR--/calls.fz:419:5:
    on is
----^


--CURDIR--/calls.fz:436:29: error 3: Call performed on a boxed (explicit 'ref') type not permitted here.
    yak "caseC3a: "; chck t.f.s "f#3 in oa type calls.caseC2.oa"     # ******  NEGATIVE TEST, causes ERROR!  ******
----------------------------^
The problem is that the call result type '(calls.this.type.caseC3.this.type.ref on).f' contains the outer, boxed type while the call will create the corresponding value type of the dynamic target type, which might be a different type inheriting from 'calls.caseC3.on'.
Type with boxed outer type: '(calls.this.type.caseC3.this.type.ref on).f'
Boxed outer type          : 'calls.this.type.caseC3.this.type.ref on'
To solve this, remove the use of 'ref' in the declaration of the type of the call target or add 'ref' to the declaration of the corresponding feature 'calls.caseC3.on' at --CURDIR--/calls.fz:419:5:
    on is
----^


--CURDIR--/calls.fz:440:29: error 4: Call performed on a boxed (explicit 'ref') type not permitted here.
    yak "caseC3b: "; chck t.f.s "f#1 in on type calls.caseC2.on"     # ******  NEGATIVE TEST, causes ERROR!  ******
----------------------------^
The problem is that the call result type '(calls.this.type.caseC3.this.type.ref on).f' contains the outer, boxed type while the call will create the corresponding value type of the dynamic target type, which might be a different type inheriting from 'calls.caseC3.on'.
Type with boxed outer type: '(calls.this.type.caseC3.this.type.ref on).f'
Boxed outer type          : 'calls.this.type.caseC3.this.type.ref on'
To solve this, remove the use of 'ref' in the declaration of the type of the call target or add 'ref' to the declaration of the corresponding feature 'calls.caseC3.on' at --CURDIR--/calls.fz:419:5:
    on is
----^


--CURDIR--/calls.fz:441:29: error 5: Call performed on a boxed (explicit 'ref') type not permitted here.
    yak "caseC3b: "; chck t.f.s "f#2 in on type calls.caseC2.on"     # ******  NEGATIVE TEST, causes ERROR!  ******
----------------------------^
The problem is that the call result type '(calls.this.type.caseC3.this.type.ref on).f' contains the outer, boxed type while the call will create the corresponding value type of the dynamic target type, which might be a different type inheriting from 'calls.caseC3.on'.
Type with boxed outer type: '(calls.this.type.caseC3.this.type.ref on).f'
Boxed outer type          : 'calls.this.type.caseC3.this.type.ref on'
To solve this, remove the use of 'ref' in the declaration of the type of the call target or add 'ref' to the declaration of the corresponding feature 'calls.caseC3.on' at --CURDIR--/calls.fz:419:5:
    on is
----^


--CURDIR--/calls.fz:442:29: error 6: Call performed on a boxed (explicit 'ref') type not permitted here.
    yak "caseC3b: "; chck t.f.s "f#3 in on type calls.caseC2.on"     # ******  NEGATIVE TEST, causes ERROR!  ******
----------------------------^
The problem is that the call result type '(calls.this.type.caseC3.this.type.ref on).f' contains the outer, boxed type while the call will create the corresponding value type of the dynamic target type, which might be a different type inheriting from 'calls.caseC3.on'.
Type with boxed outer type: '(calls.this.type.caseC3.this.type.ref on).f'
Boxed outer type          : 'calls.this.type.caseC3.this.type.ref on'
To solve this, remove the use of 'ref' in the declaration of the type of the call target or add 'ref' to the declaration of the corresponding feature 'calls.caseC3.on' at --CURDIR--/calls.fz:419:5:
    on is
----^


--CURDIR--/calls.fz:446:29: error 7: Call performed on a boxed (explicit 'ref') type not permitted here.
    yak "caseC3c: "; chck t.f.s "f#1 in on type calls.caseC2.on"     # ******  NEGATIVE TEST, causes ERROR!  ******
----------------------------^
The problem is that the call result type '(calls.this.type.caseC3.this.type.ref oa).f' contains the outer, boxed type while the call will create the corresponding value type of the dynamic target type, which might be a different type inheriting from 'calls.caseC3.oa'.
Type with boxed outer type: '(calls.this.type.caseC3.this.type.ref oa).f'
Boxed outer type          : 'calls.this.type.caseC3.this.type.ref oa'
To solve this, remove the use of 'ref' in the declaration of the type of the call target or add 'ref' to the declaration of the corresponding feature 'calls.caseC3.oa' at --CURDIR--/calls.fz:426:5:
    oa : on is
----^


--CURDIR--/calls.fz:447:29: error 8: Call performed on a boxed (explicit 'ref') type not permitted here.
    yak "caseC3c: "; chck t.f.s "f#2 in on type calls.caseC2.on"     # ******  NEGATIVE TEST, causes ERROR!  ******
----------------------------^
The problem is that the call result type '(calls.this.type.caseC3.this.type.ref oa).f' contains the outer, boxed type while the call will create the corresponding value type of the dynamic target type, which might be a different type inheriting from 'calls.caseC3.oa'.
Type with boxed outer type: '(calls.this.type.caseC3.this.type.ref oa).f'
Boxed outer type          : 'calls.this.type.caseC3.this.type.ref oa'
To solve this, remove the use of 'ref' in the declaration of the type of the call target or add 'ref' to the declaration of the corresponding feature 'calls.caseC3.oa' at --CURDIR--/calls.fz:426:5:
    oa : on is
----^


--CURDIR--/calls.fz:448:29: error 9: Call performed on a boxed (explicit 'ref') type not permitted here.
    yak "caseC3c: "; chck t.f.s "f#3 in on type calls.caseC2.on"     # ******  NEGATIVE TEST, causes ERROR!  ******
----------------------------^
The problem is that the call result type '(calls.this.type.caseC3.this.type.ref oa).f' contains the outer, boxed type while the call will create the corresponding value type of the dynamic target type, which might be a different type inheriting from 'calls.caseC3.oa'.
Type with boxed outer type: '(calls.this.type.caseC3.this.type.ref oa).f'
Boxed outer type          : 'calls.this.type.caseC3.this.type.ref oa'
To solve this, remove the use of 'ref' in the declaration of the type of the call target or add 'ref' to the declaration of the corresponding feature 'calls.caseC3.oa' at --CURDIR--/calls.fz:426:5:
    oa : on is
----^

9 errors.
